### ISSUE TITLE
HSDS files not loading properly

### ISSUE THREAD

**Issue by elainethale** [dsgrid/dsgrid-legacy-efs-api#23]
In "Browse one file.ipynb", choosing dsgrid_hsds_base_path fails in the "Choose a file" cell because  f["enumerations"] has 0 members. (Opening the file over the NREL network or from s3 shows that f["enumerations"] has 4 members.)

Currently, this can only be observed on the eh/support_oedi branch.

**Comment by MRossol** [comment]
@elainethale, can you provide a bit more context. Which file specifically are you looking at?

**Comment by MRossol** [comment]
So it looks like the enumerations group didn't get loaded properly. I'll debug tomorrow

**Comment by MRossol** [comment]
@elainethale, can you try again? I reloaded the files and see the datasets within the enumerate group

**Comment by elainethale** [comment]
Gets farther, but now I get this error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\1/ipykernel_17808/3010831080.py in <module>
     10 input_str = input("Which file would you like to examine (input number)? ")
     11 if is_hsds:
---> 12     datafile = Datafile.load(f"{dsgrid_dataset_path}{options.get_option(input_str)}")
     13 elif is_s3:
     14     datafile = Datafile.load(f"{dsgrid_dataset_path}{options.get_option(input_str)}")

c:\projects\dsgrid-legacy-efs-api\dsgrid\dataformat\datafile.py in load(cls, filepath, upgrade, overwrite, new_filepath, **kwargs)
    147                 result.sectordata[sector_id] = sector_dataset
    148 
--> 149             return result
    150 
    151     def upgrade(self,OLD_VERSIONS,overwrite=False,new_filepath=None):

c:\projects\dsgrid-legacy-efs-api\dsgrid\dataformat\datafile.py in load(cls, filepath, upgrade, overwrite, new_filepath, **kwargs)
    137             enum_group = f["enumerations"]
    138             result = cls(filepath,
--> 139                          SectorEnumeration.load(enum_group),
    140                          GeographyEnumeration.load(enum_group),
    141                          EndUseEnumerationBase.load(enum_group),

c:\projects\dsgrid-legacy-efs-api\dsgrid\dataformat\enumeration.py in load(cls, h5group)
    138         return cls(
    139             get_str(h5dset.attrs["name"]),
--> 140             [get_str(vid) for vid in h5dset["id"]],
    141             [get_str(vname) for vname in h5dset["name"]]
    142         )

c:\python\envs\dsgrid-legacy-efs-api\lib\site-packages\h5pyd\_hl\dataset.py in __getitem__(self, args)
    862                         self.log.info("binary response, {} bytes".format(len(rsp)))
    863                         #arr1d = numpy.frombuffer(rsp, dtype=mtype)
--> 864                         arr1d = bytesToArray(rsp, mtype, page_mshape)
    865                         page_arr = numpy.reshape(arr1d, page_mshape)
    866                     else:

c:\python\envs\dsgrid-legacy-efs-api\lib\site-packages\h5pyd\_hl\base.py in bytesToArray(data, dt, shape)
    497         for index in range(nelements):
    498             offset = readElement(data, offset, arr, index, dt)
--> 499     arr = arr.reshape(shape)
    500     return arr
    501 

ValueError: cannot reshape array of size 12 into shape (4,)
```

**Comment by MRossol** [comment]
hmm i've never seen that before. Can you tell me the exact file/dataset your trying to get data from?

**Comment by elainethale** [comment]
s3://oedi-data-lake/dsgrid-2018-efs/state_hourly_residuals/eia_annual_energy_by_sector.dsg

**Comment by MRossol** [comment]
And the dataset that your trying to extract?

**Comment by elainethale** [comment]
f["enumerations"]["sector"]

Then it's barfing on f["enumerations"]["sector"]["id"].


ENCODING = "utf-8"

def get_str(a_str_or_bytes):
    if isinstance(a_str_or_bytes,bytes):
        return a_str_or_bytes.decode(ENCODING)
    return a_str_or_bytes

**Comment by elainethale** [comment]
The dataset was originally made with this code:

```
    def persist(self, h5group):

        dset = h5group.create_dataset(
            self.dimension,
            dtype=self.enum_dtype,
            shape=(len(self),))

        dset.attrs["name"] = self.name

        dset["id"] = np.array(self.ids)
        dset["name"] = np.array([name.encode(ENCODING) for name in self.names])

        return dset
```

**Comment by MRossol** [comment]
Interesting, this appears to be an HSDS bud.
This works:
```
In [11]: with h5pyd.File(hsds_path, mode='r') as f:
    ...:     sector = f['enumerations']['sector'][...]
    ...:     v = sector['id']
```

But this doesn't:
```
In [13]: with h5py.File(path, mode='r') as f:
    ...:     v = f['enumerations']['sector']['id']
    ...:
```

I'll ping our HSDS contractor and let him know. In the mean time you can get around this by extracting the full table and then pulling out the column.

**Comment by elainethale** [comment]
Oh, I see the `...` dots are real syntax? I'll try that out ...

**Comment by MRossol** [comment]
`[...]` extracts the entire data set into memory, it behaves the same as `[:]`

For context, in h5py and h5pyd you are doing the following:
``` 
with h5py.File(path, mode='r') as f:
    grp = f['enumerations'] # open "Group" object
    dset = grp['sector'] # open "Dataset" object
    table = dset[...] # Load entire dataset into memory
    v = table['id'] # 'id' value from table
    v = dset['id'] # also 'id' value from dataset, not sure why this doesn't work in h5pyd...
```

**Comment by elainethale** [comment]
Okay--I worked around those initial issues, but I am not sure of the right syntax in the case of 

```
s3://oedi-data-lake/dsgrid-2018-efs/state_hourly_residuals/eia_annual_energy_by_sector.dsg
dataset = f['/data/com']['enduses']
idx = dataset[:,"idx"]
```

Modifying to 
```
dset = dataset[...]
idx = dset[:,"idx"]
```

was not correct.

**Comment by MRossol** [comment]
`idx` is the value along the 0-axis, see below:
```
dset = dataset[...]
idx = dset["idx"]
```

**Comment by elainethale** [comment]
Now I can't keep debugging, because `OSError: [Errno 429] Too Many Requests`. I did get my own API Key ...

**Comment by MRossol** [comment]
whats your e-mail address?

**Comment by elainethale** [comment]
elaine.hale@nrel.gov

**Comment by MRossol** [comment]
Whats the API key, you have three registered?

Michael Rossol, Ph.D.
________________________
(he, him, his)
Data/Software Engineer
National Renewable Energy Laboratory (NREL)
303.275.3680
***@***.******@***.***>


From: Elaine Hale ***@***.***>
Date: Wednesday, September 29, 2021 at 10:28 AM
To: dsgrid/dsgrid-legacy-efs-api ***@***.***>
Cc: Rossol, Michael ***@***.***>, Mention ***@***.***>
Subject: Re: [dsgrid/dsgrid-legacy-efs-api] HSDS files not loading properly (#23)

CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe.

***@***.******@***.***>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdsgrid%2Fdsgrid-legacy-efs-api%2Fissues%2F23%23issuecomment-930337374&data=04%7C01%7Cmichael.rossol%40nrel.gov%7C7c302691adc244bf7e3708d9836634ea%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637685297263230648%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XOzEQ9nBoQ18JGb042MkPTfjnBlvF3mOIi7c5G%2FZ2w8%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEOIRK7JXITZFB2ZJG7IGCTUEM5DZANCNFSM5E6P3R7A&data=04%7C01%7Cmichael.rossol%40nrel.gov%7C7c302691adc244bf7e3708d9836634ea%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637685297263240605%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=H8eoPqRBCsBEa213zCTRWvGvVuBCKdSxmUEF9D4GKJ0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmichael.rossol%40nrel.gov%7C7c302691adc244bf7e3708d9836634ea%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637685297263250560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZS%2B%2BHUxdCqS6Aj1Jas02dyQ3%2BZgFl%2BxCnVR4Vgdhq4A%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmichael.rossol%40nrel.gov%7C7c302691adc244bf7e3708d9836634ea%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637685297263250560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Qr64sJMatLrpwlBszIuAl2kezniimTJkdPwXRuTPHs0%3D&reserved=0>.

**Comment by elainethale** [comment]
Emailed it

**Comment by MRossol** [comment]
okay limit increased

**Comment by elainethale** [comment]
@MRossol -- HSDS is working now. Unfortunately it's actually much slower than simply using S3. If I run the "Browse one file" notebook on the 5th file (annual EIA data) these are the times:

data location | notebook run time
----------------|-----------------------
nrelnas01      | 30 s
s3                 | 74 s
HSDS            | 650 s

**Comment by MRossol** [comment]
That’s not entirely surprising given the size of your files/datasets. HSDS really shines with large datasets that can be read in parallel.

Michael Rossol, Ph.D.
________________________
(he, him, his)
Data/Software Engineer
National Renewable Energy Laboratory (NREL)
303.275.3680
***@***.******@***.***>


From: Elaine Hale ***@***.***>
Date: Wednesday, September 29, 2021 at 2:34 PM
To: dsgrid/dsgrid-legacy-efs-api ***@***.***>
Cc: Rossol, Michael ***@***.***>, Mention ***@***.***>
Subject: Re: [dsgrid/dsgrid-legacy-efs-api] HSDS files not loading properly (#23)

CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe.

@MRossol<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMRossol&data=04%7C01%7Cmichael.rossol%40nrel.gov%7Cb8c49ba95e8c4698529f08d9838895a8%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637685444919307649%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UkBnsZjH3h50SACey9tCXw6MlCHf1XON6lJnYGpEUBk%3D&reserved=0> -- HSDS is working now. Unfortunately it's actually much slower than simply using S3. If I run the "Browse one file" notebook on the 5th file (annual EIA data) these are the times:
data location
notebook run time
nrelnas01
30 s
s3
74 s
HSDS
650 s

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdsgrid%2Fdsgrid-legacy-efs-api%2Fissues%2F23%23issuecomment-930522889&data=04%7C01%7Cmichael.rossol%40nrel.gov%7Cb8c49ba95e8c4698529f08d9838895a8%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637685444919317607%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4RzGBbPTUb%2Fhj1%2FT8rsLtrHEFwR4tPlqYAkJHyD9OIA%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEOIRK7MR6PELN7ECPNEOT3UENZ6RANCNFSM5E6P3R7A&data=04%7C01%7Cmichael.rossol%40nrel.gov%7Cb8c49ba95e8c4698529f08d9838895a8%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637685444919327564%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xT30Ufqj4G06wCidlVMuUw%2FnQuu6FTq14WqljbKDHzU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmichael.rossol%40nrel.gov%7Cb8c49ba95e8c4698529f08d9838895a8%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637685444919327564%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oqiNqYRpfmGlekwSOiRDjk3f4LUSvFvvzevZM4ukYX0%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmichael.rossol%40nrel.gov%7Cb8c49ba95e8c4698529f08d9838895a8%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637685444919337517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LlPCvi%2BcqMYYtKZH1w%2FvQWib%2B2dV9TcLOUaO0pNN9Ec%3D&reserved=0>.
